"#version 330\n"
"in vec2 fragTexCoord;"
"in vec4 fragColor;"
"uniform sampler2D texture0;"
"out vec4 finalColor;"
"void main() {"
"   vec4 texelColor = texture(texture0, fragTexCoord);"
"   finalColor = texelColor*fragColor;"
"}"