"#version 330\n"
"in vec3 vertexPosition;"
"in vec2 vertexTexCoord;"
"in float vertexColor;"
"uniform mat4 mvp;"
"out vec2 fragTexCoord;"
"out vec4 fragColor;"
"void main() {"
"    fragTexCoord = vertexTexCoord / 16;"
"    fragColor = vec4(vertexColor / 256, vertexColor / 256, vertexColor / 256, 1.0);" 
"    vec3 pos = vec3(round(vertexPosition.x / 15.9f), round(vertexPosition.y / 15.9f), round(vertexPosition.z / 15.9f));"
"    gl_Position = mvp*vec4(pos, 1.0);"
"}"