"#version 100\n"
"precision mediump float;"
"varying vec4 fragColor;"
"varying mediump float fogDistance;"
"uniform vec4 colDiffuse;"
"uniform vec3 fogColor;"
"uniform float fogStart;"
"uniform float fogEnd;"
"void main() {"
"    vec3 cloudColor = fragColor.rgb * colDiffuse.rgb;"
"    float fogAmount = smoothstep(fogStart, fogEnd, fogDistance);"
"    gl_FragColor = vec4(mix(cloudColor, fogColor, fogAmount), 1.0);"
"}"
