"#version 330\n"
"in vec4 fragColor;"
"in float fogDistance;"
"uniform vec4 colDiffuse;"
"uniform vec3 fogColor;"
"uniform float fogStart;"
"uniform float fogEnd;"
"out vec4 finalColor;"
"void main() {"
"    vec3 cloudColor = fragColor.rgb * colDiffuse.rgb;"
"    float fogAmount = smoothstep(fogStart, fogEnd, fogDistance);"
"    finalColor = vec4(mix(cloudColor, fogColor, fogAmount), 1.0);"
"}"
