"#version 100\n"
"precision highp float;"
"attribute vec3 vertexPosition;"
"attribute vec4 vertexColor;"
"uniform mat4 mvp;"
"uniform mat4 matModel;"
"uniform vec3 cameraPosition;"
"varying vec4 fragColor;"
"varying mediump float fogDistance;"
"void main() {"
"    vec3 worldPosition = (matModel * vec4(vertexPosition, 1.0)).xyz;"
"    fogDistance = length(worldPosition.xz - cameraPosition.xz);"
"    fragColor = vertexColor;"
"    gl_Position = mvp * vec4(vertexPosition, 1.0);"
"}"
