#ifndef ISLEFORGE_SHARED_ENTITY_ANIMATION_H
#define ISLEFORGE_SHARED_ENTITY_ANIMATION_H

typedef enum EntityAnimationType {
    ENTITY_ANIMATION_SWING_RIGHT_ARM,
    ENTITY_ANIMATION_SWING_LEFT_ARM
} EntityAnimationType;

#endif
