/**
 * Copyright (c) 2026 Sirvoid
 *
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

#ifndef MIDLESS_PACKET_OPCODES_H
#define MIDLESS_PACKET_OPCODES_H

// Opcodes are scoped by direction; values on the wire must remain stable.
// Client -> server.
#define PACKET_IDENTIFICATION 0
#define PACKET_PLAYER_POSITION 1
#define PACKET_CLIENT_MESSAGE 2
#define PACKET_DRAW_DISTANCE 3
#define PACKET_PLAYER_CLICK 4
#define PACKET_TEXTURE_ACK 5
#define PACKET_INVENTORY_ACTION 6

// Server -> client.
#define PACKET_MAP_INIT 0
#define PACKET_LOAD_CHUNK 1
#define PACKET_SET_BLOCK 2
#define PACKET_SPAWN_ENTITY 3
#define PACKET_TELEPORT_ENTITY 4
#define PACKET_SERVER_MESSAGE 5
#define PACKET_DESPAWN_ENTITY 6
#define PACKET_UNLOAD_CHUNK 7
#define PACKET_BLOCK_BATCH 8
#define PACKET_WORLD_TIME 9
#define PACKET_MESSAGE_CONTINUATION 10
#define PACKET_ENTITY_ANIMATION 11
#define PACKET_DEFINE_BLOCK 12
#define PACKET_REMOVE_BLOCK_DEFINITION 13
#define PACKET_DEFINE_ENTITY_MODEL 14
#define PACKET_REMOVE_ENTITY_MODEL 15
#define PACKET_SET_ENTITY_MODEL 16
#define PACKET_TEXTURE_BEGIN 17
#define PACKET_TEXTURE_DATA 18
#define PACKET_TERRAIN_TEXTURE 19
#define PACKET_HELD_BLOCK 20
#define PACKET_INVENTORY_STATE 21
#define PACKET_DROPPED_ITEM 22
#define PACKET_INVENTORY_VIEW 23
#define PACKET_DEFINE_ITEM 24
#define PACKET_DIG_PROGRESS 25
#define PACKET_BREAKING_TEXTURE 26
#define PACKET_DEFINE_HUD_BAR 27
#define PACKET_SET_HUD_BAR 28
#define PACKET_REMOVE_HUD_BAR 29
#define PACKET_TEXT_COLOR 30
#define PACKET_NAMETAG 31
#define PACKET_PLAYER_IMPULSE 32
#define PACKET_SET_ENTITY_TEXTURE 33
#define PACKET_CHUNK_LIGHT 34
#define PACKET_RESET_CHUNKS 35
#define PACKET_CAMERA_KICK 36

#endif
