#ifndef MIDLESS_PACKET_SIZES_H
#define MIDLESS_PACKET_SIZES_H

// Sizes include the opcode. Zero marks a variable-length packet.
#define PACKET_VARIABLE_SIZE 0
#define PACKET_STRING_SIZE 64

// Client -> server.
#define IDENTIFICATION_PACKET_SIZE 67
#define PLAYER_POSITION_PACKET_SIZE 16
#define MESSAGE_PACKET_SIZE 65
#define DRAW_DISTANCE_PACKET_SIZE 2
#define PLAYER_CLICK_PACKET_SIZE 2

// Server -> client.
#define MAP_INIT_PACKET_SIZE 3
#define LOAD_CHUNK_HEADER_SIZE 15
#define SET_BLOCK_PACKET_SIZE 16
#define SPAWN_ENTITY_PACKET_SIZE 21
#define SET_ENTITY_TEXTURE_PACKET_SIZE 5
#define CHUNK_LIGHT_HEADER_SIZE 15
#define RESET_CHUNKS_PACKET_SIZE 1
#define TELEPORT_ENTITY_PACKET_SIZE 18
#define DESPAWN_ENTITY_PACKET_SIZE 3
#define UNLOAD_CHUNK_PACKET_SIZE 13
#define BLOCK_BATCH_HEADER_SIZE 3
#define BLOCK_BATCH_UPDATE_SIZE 14
#define WORLD_TIME_PACKET_SIZE 5
#define MESSAGE_CONTINUATION_PACKET_SIZE MESSAGE_PACKET_SIZE
#define ENTITY_ANIMATION_PACKET_SIZE 4
#define REMOVE_BLOCK_DEFINITION_PACKET_SIZE 2
#define REMOVE_ENTITY_MODEL_PACKET_SIZE 2
#define SET_ENTITY_MODEL_PACKET_SIZE 4
#define TERRAIN_TEXTURE_PACKET_SIZE 3
#define HELD_BLOCK_PACKET_SIZE 5
#define DIG_PROGRESS_PACKET_SIZE 21
#define BREAKING_TEXTURE_PACKET_SIZE 2
#define INVENTORY_STATE_HEADER_SIZE 12
#define INVENTORY_VIEW_HEADER_SIZE (1 + INVENTORY_STATE_PACKET_SIZE)

// Structured payloads; dimension/metadata limits come from their shared headers.
#define DEFINE_BLOCK_PACKET_SIZE (83 + BLOCK_GEOMETRY_BYTES)
#define DROPPED_ITEM_PACKET_SIZE (21 + ITEM_METADATA_BYTES)
#define HUD_BAR_DEFINE_SIZE 8
#define HUD_BAR_STATE_SIZE 5
#define HUD_BAR_REMOVE_SIZE 2
#define ENTITY_MODEL_HEADER_SIZE 69
#define ENTITY_MODEL_PART_SIZE 75
#define INVENTORY_ACTION_PACKET_SIZE 25
#define ITEM_STACK_PACKET_SIZE 70
#define INVENTORY_STATE_PACKET_SIZE (INVENTORY_STATE_HEADER_SIZE + 37 * ITEM_STACK_PACKET_SIZE)
#define ITEM_DEFINITION_PACKET_SIZE 135
#define TEXTURE_BEGIN_SIZE 15
#define TEXTURE_DATA_SIZE (13 + TEXTURE_CHUNK_BYTES)
#define TEXTURE_ACK_SIZE 11

#endif
